# Generated by Django 5.0.3 on 2024-05-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("ticket_number", models.IntegerField()),
                ("date_generation", models.DateField()),
                ("client_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                ("category_problem", models.CharField(max_length=25)),
                ("description", models.TextField()),
            ],
        ),
    ]
