# Generated by Django 5.0.3 on 2024-06-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("implementation", "0002_teams_ticket_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="solucionado_cs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="solucionado_cs_and_ma",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
